/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library.managment.system;

import java.text.SimpleDateFormat;
import java.util.Iterator;
import javax.swing.JOptionPane;
import librarydatabase.issuedb;
import static librarydatabase.issuedb.getstudent_id;
import org.sqlite.SQLiteException;

public class Issuebook extends javax.swing.JFrame {

   
    public Issuebook() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bookid = new javax.swing.JTextField();
        studentid = new javax.swing.JTextField();
        issuedate = new com.toedter.calendar.JDateChooser();
        duedate = new com.toedter.calendar.JDateChooser();
        issubtn = new javax.swing.JButton();
        closbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 170));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Book ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 99, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Student ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 139, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Issue date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 175, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Due date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 215, -1, -1));

        bookid.setBackground(java.awt.Color.white);
        bookid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookid.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 99, 119, -1));

        studentid.setBackground(java.awt.Color.white);
        studentid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentid.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 139, 119, -1));

        issuedate.setBackground(java.awt.Color.white);
        issuedate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(issuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 175, 119, -1));

        duedate.setBackground(java.awt.Color.white);
        duedate.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 215, 119, -1));

        issubtn.setBackground(new java.awt.Color(255, 255, 255));
        issubtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issubtn.setForeground(new java.awt.Color(0, 0, 0));
        issubtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/issue book.png"))); // NOI18N
        issubtn.setText("Issue");
        issubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issubtnActionPerformed(evt);
            }
        });
        getContentPane().add(issubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 283, -1, -1));

        closbtn.setBackground(new java.awt.Color(255, 255, 255));
        closbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closbtn.setForeground(new java.awt.Color(0, 0, 0));
        closbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red-x-mark-transparent-background-3.png"))); // NOI18N
        closbtn.setText("Close");
        closbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closbtnActionPerformed(evt);
            }
        });
        getContentPane().add(closbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 283, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/123456.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closbtnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==closbtn){
            new Homepage();
            this.dispose();
        }
    }//GEN-LAST:event_closbtnActionPerformed

    private void issubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issubtnActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dformat=new SimpleDateFormat("dd-MM-yyyy");
        if(evt.getSource()==issubtn){
            
             int y=librarydatabase.issuedb.check_bookstudentId(Integer.parseInt(studentid.getText()), Integer.parseInt(bookid.getText()));
          
            System.out.println(y);
           switch (y){
               case 1:
                 try{
               librarydatabase.issuedb.insert_issuedataofbook(Integer.parseInt(bookid.getText()), Integer.parseInt(studentid.getText()),dformat.format(issuedate.getDate()),dformat.format(duedate.getDate()));
            JOptionPane.showMessageDialog(null, " book "+bookid.getText()+" is issued to student of ID"+studentid.getText(), "Issue of books", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new Issuebook();
                 }catch(Exception e){
                     System.out.println(e.getMessage());
                 }
            break;
            
//               case 2:
//                  JOptionPane.showMessageDialog(null, "This Student or Book doesnot Exist ", "Issue of books", JOptionPane.INFORMATION_MESSAGE);
//                  this.dispose();
//                  new Homepage();
//                  break;
                  default:
                       JOptionPane.showMessageDialog(null, "Enter  Student & Book ID ", "Issue of books", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                  new Issuebook();
                       break;
        
            }
        }
    }//GEN-LAST:event_issubtnActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookid;
    private javax.swing.JButton closbtn;
    private com.toedter.calendar.JDateChooser duedate;
    private javax.swing.JButton issubtn;
    private com.toedter.calendar.JDateChooser issuedate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField studentid;
    // End of variables declaration//GEN-END:variables
}
