/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library.managment.system;
import librarydatabase.bookdb;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
public class Newbook extends javax.swing.JFrame {

    /**
     * Creates new form Newbook
     */
    public Newbook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Book_id = new javax.swing.JTextField();
        Book_name = new javax.swing.JTextField();
        Book_publisher = new javax.swing.JTextField();
        publishing_year = new javax.swing.JTextField();
        savebookbtn = new javax.swing.JButton();
        closebookbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 170));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Book id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Book Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Book Publisher");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Publishing Year");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        Book_id.setBackground(new java.awt.Color(255, 255, 255));
        Book_id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Book_id.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(Book_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 115, -1));

        Book_name.setBackground(new java.awt.Color(255, 255, 255));
        Book_name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Book_name.setForeground(new java.awt.Color(0, 0, 0));
        Book_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_nameActionPerformed(evt);
            }
        });
        getContentPane().add(Book_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 115, -1));

        Book_publisher.setBackground(new java.awt.Color(255, 255, 255));
        Book_publisher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Book_publisher.setForeground(new java.awt.Color(0, 0, 0));
        Book_publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_publisherActionPerformed(evt);
            }
        });
        getContentPane().add(Book_publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 115, -1));

        publishing_year.setBackground(new java.awt.Color(255, 255, 255));
        publishing_year.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        publishing_year.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(publishing_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 115, -1));

        savebookbtn.setBackground(new java.awt.Color(255, 255, 255));
        savebookbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        savebookbtn.setForeground(new java.awt.Color(0, 0, 0));
        savebookbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-icon--1.png"))); // NOI18N
        savebookbtn.setText("Save");
        savebookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebookbtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 90, -1));

        closebookbtn.setBackground(new java.awt.Color(255, 255, 255));
        closebookbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closebookbtn.setForeground(new java.awt.Color(0, 0, 0));
        closebookbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red-x-mark-transparent-background-3.png"))); // NOI18N
        closebookbtn.setText("Close");
        closebookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebookbtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/123456.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Book_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_nameActionPerformed

    private void Book_publisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_publisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Book_publisherActionPerformed

    private void closebookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebookbtnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==closebookbtn){
            new Homepage().setVisible(true);
        }
    }//GEN-LAST:event_closebookbtnActionPerformed

    private void savebookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebookbtnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==savebookbtn){
            try{
            librarydatabase.bookdb.insert_bookdata(Integer.parseInt(Book_id.getText()) , Book_name.getText(),Book_publisher.getText(),(String)publishing_year.getText());
        JOptionPane.showMessageDialog(null, "Book : "+ Book_name.getText()+" Authored by: "+Book_publisher.getText()+" is added to Library", "New Book", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        new Homepage();
            }catch(Exception se){
                System.out.println(se.getMessage());
            }
            }
    }//GEN-LAST:event_savebookbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Book_id;
    private javax.swing.JTextField Book_name;
    private javax.swing.JTextField Book_publisher;
    private javax.swing.JButton closebookbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField publishing_year;
    private javax.swing.JButton savebookbtn;
    // End of variables declaration//GEN-END:variables
}
